[package]
name = "roguelike"
version = "0.1.0"
authors = ["khan"]
edition = "2018"

[dependencies]
rand = "0.3.9"
tcod = { version = "0.15", features = ["serialization"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
